### ISSUE TITLE
Anything I can do to speedup keyspace dump ?

### ISSUE THREAD

**Issue by ivnilv** [gianlucaborello/cassandradump#33]
Hello,

I have been running cassandradump on our local test clusters to export and import keyspaces around.

However, on larger dbs, on multi-datacenter clusters, I can see export jobs running for days, until they export all data. 

I'm talking in the regards of a keyspace with replication factor 3 , spread across 4 nodes, around 200GB data total across all nodes.

While this all is fine, considering the amount of data we are dealing with, I am barely seeing any load on the machines that are holding the relevant pieces of data. No high CPU or IO usage or any abnormal behavior really.

Having that in mind, I was wondering, if there's anything I can be tuning to further improve the speeds of exporting those larger dbs ?

Any suggestions appreciated ! 

Thanks,

**Comment by gianlucaborello** [comment]
That is mostly because the read path is not concurrent, as a simple toy tool it was never meant to be used for such big use cases :)

Some workarounds I can give you, from "easy" to "hard":

1) Increase the value of `FETCH_SIZE` in the code, it might help making the requests more efficient when reading a lot of data, you should be able to notice an improvement.

2) Ditch this tool altogether, and adopt a more sound strategy with tools that scale well (e.g. nodetool snapshot + sstableloader), which make a lot of sense when dealing with dozens of GB like your case.

3) Run multiple instances of the tool at the same time, each one focusing on a different column family or a different subset of filters and then merge the files manually, so you should be able to concurrently get a lot of stuff done at the same time.

4) Implement proper concurrency inside the tool: in other words, instead of always doing a `SELECT * FROM foo`, you should split the range of primary keys and start doing a whole lot of sub queries and then execute them concurrently with `cassandra.concurrent.execute_concurrent()` (which I'm sort of using during the import phase, since it's easier there). Cassandra will happily scale to thousands of concurrent read requests per second, whereas now I'm doing just one.

If I were to do this professionally, I would definitely go for option 2, or if I really needed a plain text dump I'd implement 4. Unfortunately, I don't have time at the moment to embark in this big feature.

Thanks
